/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/clipit.ts
 * Command: astryx theme build theme/clipit.ts
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.4.5
 */

/// <reference path="./clipit.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const clipitTheme: DefinedTheme;
