/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/clipit.ts
 * Command: astryx theme build theme/clipit.ts
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.4.5
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
